### ISSUE TITLE
Possible bug in Account.setOrders?

### ISSUE THREAD

**Issue by mitchellsuter** [oanda/v20-java#1]
I was using the example scripts, and when trying to use the setOrders method, it populates an empty container. Specifically, ```Order.class == item.getClass()``` will return false and never populate newOrders.

```java
public Account setOrders(Collection<?> orders) {
        ArrayList<Order> newOrders = new ArrayList<Order>(orders.size());
        orders.forEach((item) -> {
            if (Order.class == item.getClass())
            {
                newOrders.add((Order) item);
            }
        });
        this.orders = newOrders;
        return this;
```

**Comment by mitchellsuter** [comment]
Solution could be to replace

```java
 if (Order.class == item.getClass())
```
with
```java
if (item instanceof Order)
```

**Comment by HerbSears-OANDA** [comment]
Thanks for identifying this issue -- it will be fixed in the next release of the Java implementation.

**Comment by OANDA-API** [comment]
This issue is now resolved.
