### ISSUE TITLE
PricingGetRequest encodes instruments incorrectly

### ISSUE THREAD

**Issue by starksm64** [oanda/v20-java#2]
I pulled down the current git repo which is labeled as 3.0.18, and tried a simple price test case. 

The test method is:
```
    @Test
    public void testDaily() throws Exception {
        Context smsContext = new Context(FX_TRADE, TOKEN);
        String[] instruments = {"USD_CAD", "GBP_USD"};
        AccountID accountID = new AccountID(real_account_id);
        PricingGetResponse response = smsContext.pricing.get(accountID, Arrays.asList(instruments));
        response.getPrices().forEach(this::printPrice);
    }
    private void printPrice(Price price) {
        System.out.printf("%s, time: %s, ask: %.5f, bid: %.5f, status: %s, type: %s\n", price.getInstrument(), price.getTime(),
                price.getCloseoutAsk().doubleValue(), price.getCloseoutBid().doubleValue(),
        price.getStatus(), price.getType());
    }
```

This fails with a 400 error. When I looked into the reason, I found that the get uri has the instruments parameter enclosed within '[]' encoded as %5B and %5D:

https://api-fxtrade.oanda.com/v3/accounts/001-001-1234567-001/pricing?instruments=%5BUSD_CAD%2C+GBP_USD%5D

In order for the instruments to be encoded as a csv list, I had to override the instruments parameter to be an actual String[] value:

```
    @Test
    public void testDailyPriceRequestOverride() throws Exception {
        Context smsContext = new Context(FX_TRADE, TOKEN);
        String[] instruments = {"USD_CAD", "GBP_USD"};
        AccountID accountID = new AccountID(real_account_id);
        PricingGetRequest get = new PricingGetRequest(accountID, Arrays.asList(instruments));
        get.setQueryParam("instruments", instruments);
        PricingGetResponse response = smsContext.pricing.get(get);
        response.getPrices().forEach(this::printPrice);
    }

```

which produces a result:

USD_CAD, time: 2017-07-17T06:17:14.949195949Z, ask: 1.26661, bid: 1.26645, status: tradeable, type: PRICE
GBP_USD, time: 2017-07-17T06:17:51.859263562Z, ask: 1.30863, bid: 1.30797, status: tradeable, type: PRICE

It appears that the PricingGetRequest needs to collect the input instrument collection into an InstrumentName[] rather than an ArrayList<InstrumentName>.

**Comment by quux00** [comment]
I've just hit the same issue. +1 on pushing this up the priority list.

**Comment by corexin** [comment]
I reported the issue to them but no response yet, you can download the source code and make a bit hack to work it out, mainly due to context. java
if (value.getClass().isArray()) {... I believe

**Comment by OANDA-API** [comment]
This issue is now resolved.
