### ISSUE TITLE
PricePolling

### ISSUE THREAD

**Issue by fxnh** [oanda/v20-java#4]
Price Polling still not working. Even using your example you provided (on fxpractice and fxtrade) using -your PricePolling example
-new v20. jar file
-on new v20 account

- I can read account balances, trades,... so access, token,.. all works fine except prices

**Comment by madppiper** [comment]
Same happens to me. I think the endpoint is incorrect. When i set the api url and debug the Request, it heads straight to:

GET https://api-fxpractice.oanda.com/v3/accounts/my_account_id/pricing?instruments=EUR_USD

Which will trigger a 403 response. Using the stream-fxpractice url a 405 error is thrown. I got the impression that /streams is missing from the example url and it lacks a proper implementation of requesting a single price information.

**Comment by madppiper** [comment]
Nevermind... on my end, updating the token fixed the problem.

**Comment by fxnh** [comment]
Can you provide more details how you fixed this. I use the source code provided by Oanda and the latest v20 jar file - just plugged in my account id and my token - as said I can read account balances,.. but no prices ?

**Comment by madppiper** [comment]
Just try this:

    public static void getPrice(){
        try {
            Context ctx = new Context(oandaUrl,oandaToken);
            PricingGetRequest request = new PricingGetRequest(oandaAccount, instruments);
            PricingGetResponse resp = ctx.pricing.get(request);
            for (Price price : resp.getPrices())
                System.out.println(price);
        } catch (Exception e) {
           log.error("Error while fetching data from OANDA", e);
        }
    }

Whereas oandaUrl = the api-url and token = the token, oandaAccount =  new AccountID(your_oanda_account_id) and instruments = new ArrayList of the instruments you want to use... 

worked for me

**Comment by fxnh** [comment]
I tried, how did you actually set instruments - is it a list of names or strings,......

**Comment by fxnh** [comment]
I am not sure how to fill the ArrayList of instruments, can you provide a example - would be much appreciated

**Comment by madppiper** [comment]
List<String> instruments = new ArrayList<>(Arrays.asList("EUR_USD"));

**Comment by fxnh** [comment]
Still get Oanda 400 error; what url are you using ?

**Comment by fxnh** [comment]
I am using
- v20-3.0.20.jar (as published by Oanda)
-  public static final String URL ="https://api-fxtrade.oanda.com"; 
-  public static final AccountID ACCOUNTID = new AccountID("xxx-xxx-xxxxxx-xxx"); - my real   
   account nr

and your code but still 400 error - but I can read account balance, so I am quite sure account ID and token are right. Any idea ?

**Comment by fxnh** [comment]
Hi

 

Still struggeling with this. Are you also using v20-3.020.jar file ?

I know that additional jars are needed to run this (Apache,….). Would you mind to send me the list (which one and versions) you have included in your project ?

 

Thanks

 

 

 

 

Von: madppiper <notifications@github.com>
Antworten an: oanda/v20-java <reply@reply.github.com>
Datum: Freitag, 27. Oktober 2017 um 17:49
An: oanda/v20-java <v20-java@noreply.github.com>
Cc: Stefan Hauser <stefan.hauser@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [oanda/v20-java] PricePolling (#4)

 

Just try this:
public static void getPrice(){
    try {
        Context ctx = new Context(oandaUrl,oandaToken);
        PricingGetRequest request = new PricingGetRequest(oandaAccount, instruments);
        PricingGetResponse resp = ctx.pricing.get(request);
        for (Price price : resp.getPrices())
            System.out.println(price);
    } catch (Exception e) {
       log.error("Error while fetching data from OANDA", e);
    }
}
Whereas oandaUrl = the api-url and token = the token, oandaAccount = new AccountID(your_oanda_account_id) and instruments = new ArrayList of the instruments you want to use...

worked for me

**Comment by fxnh** [comment]
works now
