### ISSUE TITLE
Issue with TradeSetDependentOrdersRequest

### ISSUE THREAD

**Issue by iganev** [oanda/v20-java#7]
I am using the latest SDK:  
`compile group: 'com.oanda.v20', name: 'v20', version: '3.0.22'`  

When performing TradeSetDependentOrdersRequest request on an opened trade I can't seem to cancel dependent orders, just create them and/or modify them.  

The docblock of the setter methods say that if the takeProfit, stopLoss or trailingStopLoss are set to **null** it will cancel the order if it exists.  

Passing null to setTakeProfit, setTrailingStopLoss or setStopLoss doesn't cancel the dependent order.  

Calling:  
`tradeSetDependentOrdersRequest.setQueryParam("takeProfit", null);` 
causes a null pointer exception because of a .toString() in the request building procedure.  

Calling:  
`tradeSetDependentOrdersRequest.setQueryParam("takeProfit", "null");`
doesn't seem to work either, it causes HTTP 400 with missing fields.  

For some reason the request building procedure does not allow JSON null values to be placed for any field, and imho this is what causes the issue in the first place.

**Comment by HerbSears-OANDA** [comment]
Thanks for reporting  this issue.  I have been able to reproduce the problem and will notify you when a solution is available.

**Comment by HerbSears-OANDA** [comment]
Version 3.0.23 has been released - this version should address the issue you encountered.
