### ISSUE TITLE
Extend Context to provide custom header like Accept-Datetime-Format header

### ISSUE THREAD

**Issue by damir78** [oanda/v20-java#8]
Hello,

there is actually no possibility to provide addition header pairs into request.
Look Context:

`        try {
            httpReq = newHttpRequest(method, uriBuilder.build());
        } catch (MethodNotSupportedException | URISyntaxException e) {
            throw new ExecuteException(e);
        }
        if (this.token != null && this.token != "") {
            httpReq.addHeader("Authorization","Bearer " + this.token);
        }
        httpReq.addHeader("Content-Type", "application/json");
`
It's all. But we need to set DateTime header UNIX into request (s. http://developer.oanda.com/rest-live-v20/instrument-ep/):

Value | Description
-- | --
UNIX | If “UNIX” is specified DateTime fields will be specified or returned in the “12345678.000000123” format.
RFC3339 | If “RFC3339” is specified DateTime will be specified or returned in “YYYY-MM-DDTHH:MM:SS.nnnnnnnnnZ” format.

**Comment by HerbSears-OANDA** [comment]
Thanks for reporting this - it will be addressed in the next update.

**Comment by HerbSears-OANDA** [comment]
This issue is resolved with release v20-3.0.24
