### ISSUE TITLE
get current price in V2

### ISSUE THREAD

**Issue by rockscripts** [oanda/v20-java#9]
Hi guys, i know request [current price with API v1](http://developer.oanda.com/rest-live/rates/#getCurrentPrices) GET /v1/prices.
**Which endpoint is in v2?** 
Thank you in advance.

**Comment by HerbSears-OANDA** [comment]
Current pricing can be accessed via the Pricing endpoint (http://developer.oanda.com/rest-live-v20/pricing-ep/).  Note that the Java reference library does not currently provide direct support for the streaming endpoint. Example code is available here https://github.com/oanda/v20-java-samples/blob/master/src/main/java/com/oanda/v20/v20sample/PricePolling.java

**Comment by rockscripts** [comment]
Good day! thank you for your help. i got it but i saw [profit calculator page](https://www.oanda.com/forex-trading/analysis/profit-calculator/) and i followed instruction for getting Profit(EUR) like platform displaies it, but not lucky.

how can i calculate it with api response data for current price and candle open and close prices? actually i have it to calculate Profit EUR

**It is how oanda profit calculator does**
(Closing Rate - Opening Rate) * (Closing {quote}/{home currency}) * Units
it is my operation with vars from api

(candles.mid.c - candles.mid.o) *(trade.price) * tradeunits
